openapi: 3.0.1

info:
  title: ainize-stargan-v2-swagger
  description: |
    A good image-to-image translation model should learn a mapping between different visual domains
    ---

      How to use:
      * Select a Face Type
      * Select a Face Image
      * Execute and wait little time
  contact:
    name: Ainizer - Sangil Park
  version: "0.1"
  license:
    name: "Attribution-NonCommercial 4.0 International"
    url: https://github.com/psi1104/stargan-v2/blob/master/LICENSE

servers:
  - url: https://master-stargan-v2-psi1104.endpoint.ainize.ai/

paths:
  /predict:
    post:
      requestBody:
        required: true
        description: "image-to-image translation model should learn a mapping between different visual domains"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                check_model:
                  type: string
                  enum: [Human Face, Animal Face]
                source:
                  type: string
                  format: binary
            encoding:
              files:
                contentType: image/*

      responses:
        '200':
          description: success
          content:
            images/*:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request

        '500':
          description: Server side error